name: CapnoTrainer - Setup Digital Signing

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Setup SMM 
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}

    strategy:
      matrix:
        os:
          - name: Windows
            version: 2019

        arch: [x64]
        node: ['14']

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Setup Certificate 
        run: | 
          echo "${{secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12 
          cat /d/Certificate_pkcs12.p12 
        shell: bash 
 
      - name: Set variables 
        id: variables 
        run: | 
          echo "::set-output name=version::${GITHUB_REF#refs/tags/v}" 
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV" 
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV" 
          echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH 
          echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" >> $GITHUB_PATH 
          echo "C:\Program Files\DigiCert\DigiCert One Signing Manager Tools" >> $GITHUB_PATH 

        shell: bash 


      - name: Setup SSM KSP on windows latest 
        run: | 
          msiexec /i keylockertools-windows-x64.msi /quiet /qn 

        shell: cmd 

      - name: Check
        run: | 
          C:\Program Files\DigiCert\DigiCert Keylocker Tools\smksp_registrar.exe list
          C:\Program Files\DigiCert\DigiCert Keylocker Tools\smctl.exe keypair ls 
          C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user 
          C:\Program Files\DigiCert\DigiCert Keylocker Tools\smksp_cert_sync.exe 
        
        shell: cmd 
        